// AUTH
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// DRAWER
export const TOGGLE = 'TOGGLE';

// STUDENT
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_STUDENT_USER = 'GET_STUDENT_USER';

// DOCUMENT
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const CREATE_DOCUMENT_MODEL = 'CREATE_DOCUMENT_MODEL';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'; 

// KANBAN
export const ADD_LIST = 'ADD_LIST';
export const ADD_CARD = 'ADD_CARD';
export const DRAG_HAPPENED = 'DRAG_HAPPENED'
