// AUTH
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// DRAWER
export const TOGGLE = 'TOGGLE';

// STUDENT
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';
export const GET_STUDENT_USER = 'GET_STUDENT_USER';
export const GET_SUPERVISOR_STUDENT_LIST = 'GET_SUPERVISOR_STUDENT_LIST';

// DOCUMENT
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const CREATE_DOCUMENT_MODEL = 'CREATE_DOCUMENT_MODEL';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'; 

// SCORE
export const GET_SCORE = 'GET_SCORE';
export const GET_SCORE_LIST = 'GET_SCORE_LIST';
export const GET_SUPERVISOR_SCORE_LIST = 'GET_SUPERVISOR_SCORE_LIST'
export const CREATE_SCORE = 'CREATE_SCORE';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const GET_EVALUATION = 'GET_EVALUATION';
export const UPDATE_EVALUATION = 'UPDATE_EVALUATION';

// KANBAN
export const ADD_LIST = 'ADD_LIST';
export const ADD_CARD = 'ADD_CARD';
export const DRAG_HAPPENED = 'DRAG_HAPPENED'

// PLAN
export const GET_PLAN = 'GET_PLAN';
export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_PERIOD = 'CREATE_PLAN_PERIOD';
export const UPDATE_PLAN_PERIOD = 'UPDATE_PLAN_PERIOD';
export const DELETE_PLAN_PERIOD = 'DELETE_PLAN_PERIOD';

// TASK
export const GET_TASK = 'GET_TASK';
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_LIST = 'CREATE_TASK_LIST';
export const UPDATE_TASK_CARD = 'UPDATE_TASK_CARD';
export const DELETE_TASK_CARD = 'DELETE_TASK_CARD';
export const CREATE_TASK_CARD = 'CREATE_TASK_CARD';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
